package com.cn.za.knowledge.model;

public class KnowledgeWithBLOBs extends Knowledge {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge.question
     *
     * @mbggenerated Fri Jun 22 17:04:50 CST 2018
     */
    private String question;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge.project
     *
     * @mbggenerated Fri Jun 22 17:04:50 CST 2018
     */
    private String project;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge.question
     *
     * @return the value of knowledge.question
     *
     * @mbggenerated Fri Jun 22 17:04:50 CST 2018
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge.question
     *
     * @param question the value for knowledge.question
     *
     * @mbggenerated Fri Jun 22 17:04:50 CST 2018
     */
    public void setQuestion(String question) {
        this.question = question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge.project
     *
     * @return the value of knowledge.project
     *
     * @mbggenerated Fri Jun 22 17:04:50 CST 2018
     */
    public String getProject() {
        return project;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge.project
     *
     * @param project the value for knowledge.project
     *
     * @mbggenerated Fri Jun 22 17:04:50 CST 2018
     */
    public void setProject(String project) {
        this.project = project;
    }
}