package com.cn.za.knowledge.model;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;

public class Knowledge {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge.id
     *
     * @mbggenerated Fri Jun 22 17:04:50 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge.title
     *
     * @mbggenerated Fri Jun 22 17:04:50 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge.type
     *
     * @mbggenerated Fri Jun 22 17:04:50 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge.creator
     *
     * @mbggenerated Fri Jun 22 17:04:50 CST 2018
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge.modify_time
     *
     * @mbggenerated Fri Jun 22 17:04:50 CST 2018
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge.id
     *
     * @return the value of knowledge.id
     *
     * @mbggenerated Fri Jun 22 17:04:50 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge.id
     *
     * @param id the value for knowledge.id
     *
     * @mbggenerated Fri Jun 22 17:04:50 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge.title
     *
     * @return the value of knowledge.title
     *
     * @mbggenerated Fri Jun 22 17:04:50 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge.title
     *
     * @param title the value for knowledge.title
     *
     * @mbggenerated Fri Jun 22 17:04:50 CST 2018
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge.type
     *
     * @return the value of knowledge.type
     *
     * @mbggenerated Fri Jun 22 17:04:50 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge.type
     *
     * @param type the value for knowledge.type
     *
     * @mbggenerated Fri Jun 22 17:04:50 CST 2018
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge.creator
     *
     * @return the value of knowledge.creator
     *
     * @mbggenerated Fri Jun 22 17:04:50 CST 2018
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge.creator
     *
     * @param creator the value for knowledge.creator
     *
     * @mbggenerated Fri Jun 22 17:04:50 CST 2018
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge.modify_time
     *
     * @return the value of knowledge.modify_time
     *
     * @mbggenerated Fri Jun 22 17:04:50 CST 2018
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge.modify_time
     *
     * @param modifyTime the value for knowledge.modify_time
     *
     * @mbggenerated Fri Jun 22 17:04:50 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}